r100_0599:
  controller_manager:
    ros__parameters:
      update_rate: 50
      use_sim_time: False
      joint_state_broadcaster.type: 'joint_state_broadcaster/JointStateBroadcaster'
      platform_velocity_controller.type: 'clearpath_mecanum_drive_controller/MecanumDriveController'
  platform_velocity_controller:
    ros__parameters:
      use_sim_time: False
      interface_name: 'velocity'
      command_joint_names: ['front_left_wheel_joint', 'rear_left_wheel_joint', 'rear_right_wheel_joint', 'front_right_wheel_joint']
      front_left_wheel_command_joint_name: 'front_left_wheel_joint'
      front_right_wheel_command_joint_name: 'front_right_wheel_joint'
      rear_right_wheel_command_joint_name: 'rear_right_wheel_joint'
      rear_left_wheel_command_joint_name: 'rear_left_wheel_joint'
      kinematics.base_frame_offset:
        x: 0.0
        y: 0.0
        theta: 0.0
      kinematics.wheels_radius: 0.0759
      kinematics.sum_of_robot_center_projection_on_X_Y_axis: 0.59
      wheel_separation_multiplier: 1.0
      wheel_radius_multiplier: 1.0
      publish_rate: 50.0
      reference_timeout: 0.1
      use_stamped_vel: False
      pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
      cmd_vel_timeout: 0.5
      base_frame_id: 'base_link'
      odom_frame_id: 'odom'
      enable_odom_tf: False
      linear.x.has_velocity_limits: True
      linear.x.has_acceleration_limits: True
      linear.x.has_jerk_limits: False
      linear.x.max_velocity: 1.3
      linear.x.min_velocity: -1.3
      linear.x.max_acceleration: 1.0
      linear.x.min_acceleration: -1.0
      linear.x.max_jerk: 0.0
      linear.x.min_jerk: 0.0
      linear.y.has_velocity_limits: True
      linear.y.has_acceleration_limits: True
      linear.y.has_jerk_limits: False
      linear.y.max_velocity: 1.3
      linear.y.min_velocity: -1.3
      linear.y.max_acceleration: 1.0
      linear.y.min_acceleration: -1.0
      linear.y.max_jerk: 0.0
      linear.y.min_jerk: 0.0
      angular.z.has_velocity_limits: True
      angular.z.has_acceleration_limits: True
      angular.z.has_jerk_limits: False
      angular.z.max_velocity: 4.0
      angular.z.min_velocity: -4.0
      angular.z.max_acceleration: 2.0
      angular.z.min_acceleration: -2.0
      angular.z.max_jerk: 0.0
      angular.z.min_jerk: 0.0
  puma_control:
    ros__parameters:
      canbus_dev: 'vcan0'
      joint_names: ['front_left_wheel_joint', 'front_right_wheel_joint', 'rear_left_wheel_joint', 'rear_right_wheel_joint']
      joint_can_ids: [5, 4, 2, 3]
      joint_directions: [-1, 1, -1, 1]
      gear_ratio: 34.97
      encoder_cpr: 1024
      gain:
        p: 0.1
        i: 0.01
        d: 0.0
