r100_0599:
  teleop_twist_joy_node:
    ros__parameters:
      use_sim_time: False
      axis_linear.x: 1
      axis_linear.y: 0
      scale_linear.x: 0.4
      scale_linear.y: 0.4
      scale_linear_turbo.x: 0.4
      scale_linear_turbo.y: 0.4
      axis_angular.yaw: 3
      scale_angular.yaw: 0.5
      scale_angular_turbo.yaw: 0.5
      enable_button: 4
      enable_turbo_button: 5
  joy_node:
    ros__parameters:
      use_sim_time: False
      deadzone: 0.1
      autorepeat_rate: 20.0
      dev: '/dev/input/ps4'
